### ISSUE TITLE
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50

### ISSUE THREAD

**Issue by toralf** [ogham/dog#104]
At a stable hardened Gentoo Linux I do get: 
```
 $ RUST_BACKTRACE=full dog -H wdl1.pcfg.cache.wpscdn.com 
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50
stack backtrace:
   0:     0x556dec00c68e - <unknown>
   1:     0x556debfa41ac - <unknown>
   2:     0x556debfe70f7 - <unknown>
   3:     0x556dec00d3e0 - <unknown>
   4:     0x556dec00dc65 - <unknown>
   5:     0x556dec00d762 - <unknown>
   6:     0x556dec00d6d6 - <unknown>
   7:     0x556dec00d692 - <unknown>
   8:     0x556debf9e1a2 - <unknown>
   9:     0x556debfa42f0 - <unknown>
  10:     0x556debfa429b - <unknown>
  11:     0x556debf9e386 - <unknown>
  12:     0x556debfb7f47 - <unknown>
  13:     0x556debfd1364 - <unknown>
  14:     0x556debfcfffb - <unknown>
  15:     0x556debfd3533 - <unknown>
  16:     0x556debfc8979 - <unknown>
  17:     0x556dec00b6a6 - <unknown>
  18:     0x556debfcf944 - <unknown>
  19:     0x7f0b6e67e31c - __libc_start_call_main
                               at /var/tmp/portage/sys-libs/glibc-2.34-r13/work/glibc-2.34/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  20:     0x7f0b6e67e3cc - __libc_start_main_impl
                               at /var/tmp/portage/sys-libs/glibc-2.34-r13/work/glibc-2.34/csu/../csu/libc-start.c:392:3
  21:     0x556debfa0181 - <unknown>
  22:                0x0 - <unknown>
Aborted
```

**Comment by weltonrodrigo** [comment]
stacktrace:


```rust
# this is macOS
RUST_BACKTRACE=full dog --https alerta-brasil.github.io
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50
stack backtrace:
   0:        0x1045a5290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0e1d8bb51442c287
   1:        0x104551ce0 - core::fmt::write::hc03130b1cdaaa6ba
   2:        0x1045998c8 - std::panicking::rust_panic_with_hook::hcbaa2585146761ab
   3:        0x1045a59bc - std::panicking::begin_panic_handler::{{closure}}::hf1cef5252efc0467
   4:        0x1045a592c - std::sys_common::backtrace::__rust_end_short_backtrace::h385437d4a5876230
   5:        0x104599028 - _rust_begin_unwind
   6:        0x1045b02ec - core::panicking::panic_fmt::h45438db99a7f7477
   7:        0x1045b0494 - core::option::expect_failed::h60317ff79dcdacce
   8:        0x104563aec - <dns_transport::https::HttpsTransport as dns_transport::Transport>::send::h77e15b9c3be7b375
   9:        0x10457e44c - dog::run::h8fd5a2817019e436
  10:        0x10457d5f0 - dog::main::h9681a7c57209a82d
  11:        0x104572d60 - std::sys_common::backtrace::__rust_begin_short_backtrace::h46b3e94592404c13
  12:        0x10457cff4 - _main
[1]    9690 abort      RUST_BACKTRACE=full dog --https alerta-brasil.github.io
```

**Comment by ckujau** [comment]
Duplicate of #5, I'd say...
