### ISSUE TITLE
Panic crash when using `-H` argument

### ISSUE THREAD

**Issue by codeswhite** [ogham/dog#135]
When running:

`dog customdomain -H`

It panics with an error about HTTPS but the crash seems to not be properly handled.

Output:
```
dog customdomain -H                                                                                                                                
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50                                                           
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                    
[1]    683935 IOT instruction (core dumped)  dog customdomain -H
```

Additional info:

```
$ export RUST_BACKTRACE=full
$ dog customdomain -H           
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50
stack backtrace:
   0:      0x69fbdf39acc - <unknown>
   1:      0x69fbded281c - <unknown>
   2:      0x69fbdf3a47c - <unknown>
   3:      0x69fbdf3aef1 - <unknown>
   4:      0x69fbdf3aa92 - <unknown>
   5:      0x69fbdf3aa06 - <unknown>
   6:      0x69fbdf3a9c2 - <unknown>
   7:      0x69fbdec91c2 - <unknown>
   8:      0x69fbded2f20 - <unknown>
   9:      0x69fbded2ecb - <unknown>
  10:      0x69fbdec92d6 - <unknown>
  11:      0x69fbdee72c0 - <unknown>
  12:      0x69fbdecd776 - <unknown>
  13:      0x69fbdecc2b9 - <unknown>
  14:      0x69fbdefe543 - <unknown>
  15:      0x69fbdeceb93 - <unknown>
  16:     0x6758ea039c88 - <unknown>
  17:     0x6758ea039d4c - __libc_start_main
  18:      0x69fbdecb5c5 - <unknown>
  19:                0x0 - <unknown>
[1]    684277 IOT instruction (core dumped)  dog customdomain -H
```

Running on archlinux kernel 6.9.3, installed via `pacman`

```
$ dog --version
... v0.1.0 ...

$ sha256sum `which dog`                                      
45f8b9dccacae8a7313a9e285a892ebe4f6215192cc2b761b4f6bd59e7e7e7c2  /usr/bin/dog
```

**Comment by zQueal** [comment]
Just got this on windows, as well;

```cli
❯ dog -H TXT google.com
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport\src\https.rs:55:50
```

**Comment by jurekl** [comment]
The occurring surprising errors and strange/absurd messages caused me to give up on this program and switch to a problem-free q

**Comment by yahayaohinoyi** [comment]
can I try take this on? @ogham can you assign me?

**Comment by weltonrodrigo** [comment]
duplicate of #104

**Comment by weltonrodrigo** [comment]
backtrace:

```rust
# this is macOS
RUST_BACKTRACE=full dog --https alerta-brasil.github.io
thread 'main' panicked at 'Invalid HTTPS nameserver', dns-transport/src/https.rs:55:50
stack backtrace:
   0:        0x1045a5290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0e1d8bb51442c287
   1:        0x104551ce0 - core::fmt::write::hc03130b1cdaaa6ba
   2:        0x1045998c8 - std::panicking::rust_panic_with_hook::hcbaa2585146761ab
   3:        0x1045a59bc - std::panicking::begin_panic_handler::{{closure}}::hf1cef5252efc0467
   4:        0x1045a592c - std::sys_common::backtrace::__rust_end_short_backtrace::h385437d4a5876230
   5:        0x104599028 - _rust_begin_unwind
   6:        0x1045b02ec - core::panicking::panic_fmt::h45438db99a7f7477
   7:        0x1045b0494 - core::option::expect_failed::h60317ff79dcdacce
   8:        0x104563aec - <dns_transport::https::HttpsTransport as dns_transport::Transport>::send::h77e15b9c3be7b375
   9:        0x10457e44c - dog::run::h8fd5a2817019e436
  10:        0x10457d5f0 - dog::main::h9681a7c57209a82d
  11:        0x104572d60 - std::sys_common::backtrace::__rust_begin_short_backtrace::h46b3e94592404c13
  12:        0x10457cff4 - _main
[1]    9690 abort      RUST_BACKTRACE=full dog --https alerta-brasil.github.io
```

**Comment by ckujau** [comment]
duplicate of #5 even...
